#ifndef CONFIG_HPP
#define CONFIG_HPP

#define PORT 8443
#define THREAD_POOL_SIZE 4
#define BUFFER_SIZE 1024
#define WINDOW_SIZE 2
#define REQUEST_LIMIT 6
#define INTERNAL_SERVER_IP "127.0.0.1"
#define INTERNAL_SERVER_PORT 8081

#endif